# Generated by Django 4.2.6 on 2023-10-25 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=127, verbose_name='место')),
                ('action_time', models.DateTimeField(verbose_name='время')),
                ('action', models.CharField(max_length=127, verbose_name='действие')),
                ('is_nice', models.BooleanField(default=False, verbose_name='приятная привычка')),
                ('timing', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Раз в неделю')], default='daily', max_length=127, verbose_name='периодичность')),
                ('reward', models.CharField(blank=True, max_length=127, null=True, verbose_name='награда')),
                ('execution_time', models.IntegerField(blank=True, null=True, verbose_name='время на выполнение')),
                ('is_publish', models.BooleanField(default=False, verbose_name='публичность')),
                ('last_completed', models.DateTimeField(blank=True, null=True, verbose_name='последнее выполнение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('related_habits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
