# Generated by Django 4.2.6 on 2023-10-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=127, verbose_name='место')),
                ('action_time', models.DateTimeField(verbose_name='время')),
                ('action', models.CharField(max_length=127, verbose_name='действие')),
                ('is_nice', models.BooleanField(default=False, verbose_name='приятная привычка')),
                ('timing', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], default='daily', max_length=127, verbose_name='периодичность')),
                ('reward', models.CharField(blank=True, max_length=127, null=True, verbose_name='награда')),
                ('execution_time', models.IntegerField(blank=True, null=True, verbose_name='время на выполнение')),
                ('is_publish', models.BooleanField(default=False, verbose_name='публичность')),
                ('last_completed', models.DateTimeField(blank=True, null=True, verbose_name='последнее выполнение')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
